<section class="rounded-xl border border-slate-700 bg-slate-900/80 p-5 shadow-sm sm:p-6" aria-labelledby="movie-picker-heading">
    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end">
        <div><p class="text-xs font-semibold uppercase tracking-[.16em] text-rose-300" x-text="classifications.length && classificationType ? `Matching ${classificationType === 'theme' ? 'TMDB themes / keywords' : 'genres'}` : 'Local movie catalog'"></p><h2 id="movie-picker-heading" class="mt-1 text-xl font-semibold text-white">Movies</h2><p class="mt-1 text-sm text-slate-400" x-text="`${meta.total} matching movies${classifications.length ? ` for ${classifications.join(' OR ')}` : ''}`"></p></div>
        <label class="w-full sm:max-w-xs"><span class="sr-only">Search movies</span><input type="search" x-model="search" @input.debounce.350ms="load()" placeholder="Search movies (2+ characters)..." class="w-full rounded-lg border border-slate-600 bg-slate-800 px-3 py-2.5 text-sm text-white placeholder-slate-400 focus:border-rose-500 focus:ring-rose-500"></label>
    </div>
    <fieldset x-show="allowTypeSelection" class="mt-5">
        <legend class="text-sm font-semibold text-white">Filter by</legend>
        <div class="mt-2 inline-flex rounded-lg bg-slate-800 p-1"><template x-for="type in ['genre', 'theme']" :key="type"><button type="button" @click="if (classificationType !== type) { classificationType = type; classificationChanged(); }" :aria-pressed="classificationType === type" :class="classificationType === type ? 'bg-slate-600 text-white shadow' : 'text-slate-400 hover:text-white'" class="rounded-md px-3 py-1.5 text-xs font-medium capitalize" x-text="type === 'theme' ? 'TMDB Themes' : 'Genres'"></button></template></div>
    </fieldset>
    <div class="mt-5" x-show="classificationType">
        <h3 class="text-sm font-semibold text-white" x-text="classificationType === 'genre' ? 'Select Genres' : 'Select TMDB Themes / Keywords'"></h3>
        <div class="mt-3 grid max-h-52 grid-cols-2 gap-2 overflow-y-auto rounded-lg border border-slate-700 bg-slate-950/40 p-3 sm:grid-cols-3 lg:grid-cols-5">
            <template x-for="option in classificationOptions" :key="option"><label class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm text-slate-300 hover:bg-slate-800"><input type="checkbox" :checked="classifications.includes(option)" @change="toggleClassification(option)" class="h-4 w-4 rounded border-slate-500 bg-slate-800 text-rose-600 focus:ring-rose-500"><span x-text="option"></span></label></template>
            <p x-show="classificationOptions.length === 0" class="col-span-full py-3 text-sm text-slate-500">No {{ $listPickerType ?? 'matching' }} options are stored for local movies.</p>
        </div>
        <div class="mt-3 flex flex-wrap gap-2" x-show="classifications.length"><template x-for="item in classifications" :key="`classification-${item}`"><span class="inline-flex items-center gap-1 rounded-full bg-rose-950 px-3 py-1 text-xs font-medium text-rose-200"><span x-text="item"></span><button type="button" @click="removeClassification(item)" class="rounded-full p-0.5 hover:bg-rose-800" :aria-label="`Remove ${item}`">×</button></span></template></div>
        <template x-for="item in classifications" :key="`classification-input-${item}`"><input type="hidden" name="classifications[]" :value="item"></template>
        @error('classifications')<p class="mt-2 text-sm text-red-400">{{ $message }}</p>@enderror
        @error('classifications.*')<p class="mt-2 text-sm text-red-400">{{ $message }}</p>@enderror
    </div>
    <div class="mt-4 flex flex-wrap items-center justify-between gap-3 border-b border-slate-700 pb-3">
        <div class="inline-flex rounded-lg bg-slate-800 p-1" role="tablist" aria-label="Filter movie selection"><template x-for="tab in ['all', 'selected', 'unselected']" :key="tab"><button type="button" @click="filter = tab" :aria-pressed="filter === tab" :class="filter === tab ? 'bg-slate-600 text-white shadow' : 'text-slate-400 hover:text-white'" class="rounded-md px-3 py-1.5 text-xs font-medium capitalize transition" x-text="tab === 'unselected' ? 'Not Selected' : tab"></button></template></div>
        <p class="text-xs text-slate-400" x-show="classifications.length">Candidates match any selected genre/theme.</p>
        <label class="flex items-center gap-2 text-xs text-slate-400">Sort by<select x-model="sortBy" class="rounded-lg border border-slate-600 bg-slate-800 px-2.5 py-1.5 text-xs text-white focus:border-rose-500 focus:ring-rose-500"><option value="title">Title</option><option value="release_date">Release Date</option><option value="rating">Rating</option></select></label>
        <p class="text-xs text-slate-400"><span x-text="selectedFilms.length"></span> selected <span class="px-1 text-slate-600">·</span><span x-text="meta.total"></span> matches</p>
    </div>
    <p x-show="loading" class="py-4 text-sm text-slate-400" role="status">Loading movies from your catalog…</p><p x-show="error" x-text="error" class="py-4 text-sm text-red-300" role="alert"></p>
    <div x-show="!loading && !error && visibleFilms.length === 0" class="mt-4 rounded-lg border border-dashed border-slate-700 p-8 text-center"><p class="text-sm font-medium text-slate-200" x-text="filter === 'selected' ? 'No selected movies match this search.' : (search.length === 1 ? 'Enter at least two characters to search.' : (classifications.length ? `No movies found for ${classifications.join(' OR ')}.` : 'No movies found. Try another title or add the movie to Films first.'))"></p><p class="mt-1 text-xs text-slate-500" x-show="classifications.length && meta.total === 0 && search.length === 0">No local movie records match the selected genre/theme filters.</p></div>
    <div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6" x-show="visibleFilms.length > 0">
        <template x-for="film in visibleFilms" :key="film.id"><div class="group min-w-0 overflow-hidden rounded-xl border bg-slate-800 transition duration-200 hover:-translate-y-0.5 hover:shadow-lg" :class="isSelected(film) ? 'border-rose-500 ring-1 ring-rose-500/40' : 'border-slate-700 hover:border-slate-500'">
            <label class="block cursor-pointer"><input type="checkbox" class="sr-only" :checked="isSelected(film)" @change="toggle(film)">
                <div class="relative aspect-[2/3] w-full overflow-hidden bg-slate-950"><template x-if="film.poster_url"><img :src="film.poster_url" :alt="`${film.title} poster`" loading="lazy" class="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]" x-on:error="$el.classList.add('hidden'); $el.nextElementSibling.classList.remove('hidden')"></template><div class="absolute inset-0 flex items-center justify-center p-2 text-center text-xs text-slate-500" :class="film.poster_url ? 'hidden' : ''">No Poster</div><div class="absolute inset-0 transition" :class="isSelected(film) ? 'bg-rose-950/20' : 'bg-black/0 group-hover:bg-black/10'"></div><span x-show="isSelected(film)" class="absolute right-2 top-2 flex h-6 w-6 items-center justify-center rounded-full bg-rose-600 text-white shadow-lg" aria-label="Selected"><svg class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.704 5.29a1 1 0 010 1.414l-7.2 7.2a1 1 0 01-1.414 0l-3.6-3.6A1 1 0 016 8.89l2.793 2.793 6.493-6.393a1 1 0 011.418 0z" clip-rule="evenodd"/></svg></span></div>
                <div class="p-2.5"><p class="truncate text-sm font-semibold text-white" x-text="film.title"></p><p class="mt-1 line-clamp-2 text-xs text-slate-400" x-text="`${film.year || 'Year unavailable'} · ${film.genre || 'Genre unavailable'}`"></p><div x-show="film.tmdb_keywords?.length" class="mt-2 flex flex-wrap gap-1"><template x-for="keyword in (film.tmdb_keywords || []).slice(0, 4)" :key="`${film.id}-${keyword}`"><span class="rounded-full bg-sky-950 px-2 py-0.5 text-[9px] text-sky-200" x-text="keyword"></span></template></div><p x-show="film.tmdb_id" class="mt-1 text-[10px] text-slate-500" x-text="`TMDB ID ${film.tmdb_id}`"></p><p x-show="film.rating" class="mt-1 text-xs text-amber-300" x-text="`★ ${film.rating}`"></p></div>
            </label>
            <div class="border-t border-slate-700/80 px-2.5 py-2" x-show="isSelected(film)"><template x-if="metadataByFilm[String(film.id)]?.loading"><p class="text-xs text-slate-400">Loading TMDB metadata...</p></template><template x-if="!metadataByFilm[String(film.id)]"><button type="button" @click="loadMetadata(film)" class="text-xs font-medium text-sky-300 hover:text-sky-200">Show TMDB genres & themes</button></template><template x-if="metadataByFilm[String(film.id)] && !metadataByFilm[String(film.id)].loading && !metadataByFilm[String(film.id)].available"><p class="text-xs text-slate-500">TMDB themes unavailable for this movie. It can still be added.</p></template><template x-if="metadataByFilm[String(film.id)]?.available"><div class="space-y-2"><div><p class="text-[10px] font-semibold uppercase tracking-wide text-slate-500">TMDB Genres</p><div class="mt-1 flex flex-wrap gap-1"><template x-for="genre in metadataByFilm[String(film.id)].genres" :key="genre.id"><span class="rounded-full bg-violet-950 px-2 py-0.5 text-[10px] text-violet-200" x-text="genre.name"></span></template><span x-show="metadataByFilm[String(film.id)].genres.length === 0" class="text-[10px] text-slate-500">Unavailable</span></div></div><div><p class="text-[10px] font-semibold uppercase tracking-wide text-slate-500">TMDB Themes / Keywords</p><div class="mt-1 flex flex-wrap gap-1"><template x-for="keyword in metadataByFilm[String(film.id)].keywords" :key="keyword.id"><button type="button" @click="useTheme(keyword.name)" class="rounded-full bg-sky-950 px-2 py-0.5 text-[10px] text-sky-200 transition hover:bg-sky-800" :title="`Filter this list by ${keyword.name}`" x-text="keyword.name"></button></template><span x-show="metadataByFilm[String(film.id)].keywords.length === 0" class="text-[10px] text-slate-500">No TMDB keywords available</span></div></div></div></template></div>
        </div></template>
    </div>
    <div class="mt-4 flex justify-center" x-show="currentPage < lastPage"><button type="button" @click="loadMore()" :disabled="loading" class="rounded-lg border border-slate-600 px-4 py-2 text-sm font-medium text-slate-200 transition hover:bg-slate-800 disabled:opacity-50">Load more movies</button></div>
    <div class="mt-6 border-t border-slate-700 pt-4" x-show="selectedFilms.length > 0"><div class="flex flex-wrap items-center justify-between gap-2"><div><h3 class="text-sm font-semibold text-white">Selected Movies</h3><p class="text-xs text-slate-400"><span x-text="selectedFilms.length"></span> movies selected</p></div><button type="button" @click="clearSelection()" class="text-xs font-medium text-rose-300 hover:text-rose-200">Clear Selection</button></div><div class="mt-3 flex flex-wrap gap-2"><template x-for="film in selectedFilms" :key="`picked-${film.id}`"><button type="button" @click="toggle(film)" class="group relative h-16 w-11 overflow-hidden rounded border border-slate-600 bg-slate-800" :title="`Remove ${film.title}`"><template x-if="film.poster_url"><img :src="film.poster_url" :alt="film.title" loading="lazy" class="h-full w-full object-cover" x-on:error="$el.classList.add('hidden'); $el.nextElementSibling.classList.remove('hidden')"></template><span class="flex h-full items-center justify-center p-1 text-center text-[8px] text-slate-500" :class="film.poster_url ? 'hidden' : ''">No Poster</span><span class="absolute inset-0 hidden items-center justify-center bg-black/75 text-[9px] font-medium text-white group-hover:flex">Remove</span></button></template></div></div>
    <template x-for="filmId in Object.keys(selected)" :key="`film-input-${filmId}`"><input type="hidden" name="film_ids[]" :value="filmId"></template>
    @error('film_ids')<p class="mt-3 text-sm text-red-400">{{ $message }}</p>@enderror
    @error('film_ids.*')<p class="mt-3 text-sm text-red-400">{{ $message }}</p>@enderror
</section>
