@extends('admin.layout')

@section('title', 'Manage Films · '.$list->title)

@section('content')
<div class="mx-auto max-w-7xl space-y-6" x-data="adminListFilmPicker({ endpoint: @js(route('admin.lists.matching-films')), metadataEndpoint: @js(route('admin.lists.films.metadata', ['film' => 'FILM_ID'])), classificationType: @js($list->classification_type), classifications: @js($list->classifications ?: array_filter([$list->classification])), genres: @js($genres), themes: @js($themes), allowTypeSelection: true, listId: @js($list->id), selected: @js($selectedFilmData), search: @js($search) })" x-init="load()">
    <nav aria-label="Breadcrumb" class="text-sm text-slate-400"><a href="{{ route('admin.lists.index') }}" class="hover:text-white">Lists</a><span class="px-2 text-slate-600">/</span><a href="{{ route('admin.lists.show', $list) }}" class="hover:text-white">{{ $list->title }}</a><span class="px-2 text-slate-600">/</span><span class="text-slate-200">Manage Films</span></nav>
    <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold uppercase tracking-[.16em] text-rose-300">Official collection</p><h1 class="mt-1 text-3xl font-bold text-white">Manage Films</h1><p class="mt-2 text-sm text-slate-400">{{ $list->title }} · <span x-text="selectedFilms.length"></span> movies selected.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.lists.show', $list) }}" class="rounded-lg border border-slate-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-slate-800">Back to List</a><a href="{{ route('admin.lists.index') }}" class="rounded-lg border border-slate-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-slate-800">All Lists</a></div></header>
    <form method="POST" action="{{ route('admin.lists.films.sync', $list) }}" @submit="saving = true" class="space-y-6">@csrf
        <section class="rounded-xl border border-slate-700 bg-slate-900/80 p-5 sm:p-6"><div class="mb-4"><h2 class="text-lg font-semibold text-white">Current Movies</h2><p class="mt-1 text-sm text-slate-400">Movies already in this list are selected below. Uncheck one to remove it; its catalog record remains intact.</p></div>
            @if($currentFilms->isEmpty())<p class="rounded-lg border border-dashed border-slate-700 p-5 text-sm text-slate-400">No movies have been added to this list yet.</p>@else<div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($currentFilms as $film)<a href="{{ route('admin.films.show', $film) }}" class="flex min-w-0 items-center gap-3 rounded-lg border border-slate-700 bg-slate-800/60 p-2.5 hover:border-slate-500"><span class="h-16 w-11 shrink-0 overflow-hidden rounded bg-slate-900"><x-film-poster-image :film="$film" container-class="h-full w-full" :alt="$film->title.' poster'" /></span><span class="min-w-0"><span class="block truncate text-sm font-medium text-white">{{ $film->title }}</span><span class="mt-1 block truncate text-xs text-slate-400">{{ $film->release_year ?: $film->release_date?->format('Y') ?: 'Year unavailable' }} · {{ $film->genre ?: 'Genre unavailable' }}</span></span></a>@endforeach</div>@endif
            @if($currentFilms->hasPages())<div class="mt-4">{{ $currentFilms->links() }}</div>@endif
        </section>
        <div><h2 class="mb-3 text-xl font-bold text-white">Add or Remove Movies</h2>@include('admin.lists._film-picker')</div>
        <div class="sticky bottom-3 z-10 flex flex-col justify-between gap-3 rounded-xl border border-slate-700 bg-slate-950/95 p-3 shadow-xl backdrop-blur sm:flex-row sm:items-center"><p class="text-sm text-slate-300"><span class="font-semibold text-white" x-text="selectedFilms.length"></span> movies selected</p><button type="submit" :disabled="saving" class="rounded-lg bg-rose-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-rose-500 disabled:cursor-wait disabled:opacity-60" x-text="saving ? 'Saving…' : 'Save Movie Selection'"></button></div>
    </form>
</div>
@endsection
